#!/usr/bin/env bash

# Colors taken from tokyonight theme
# red="0xfff7768e"
# blue="0xff7aa2f7"
transparent="0x00000000"
active="0xff89b4fa"
inactive="0xff6c7086"

options=(
  active_color=$active
  inactive_color=$inactive
  hidpi=on
  style=round
  width=3.0
)

borders "${options[@]}"
